TESTENV=netcli-quicklab-crpd
TEST_BINARY=router_example_juniper

ROUTERS_XR=
ROUTERS_CRPD=crpd

include ../common/clab.mk
include ../common/containers.mk
include ../common/quicklab.mk

start: licenses/juniper_crpd24.lic
